[package]
name = "grpc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Native Sui gRPC client (sui-rpc-api) with raw calls and real-time checkpoint streaming."

[dependencies]
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
futures.workspace = true
move-core-types.workspace = true
serde_json.workspace = true
sui-rpc-api.workspace = true
sui-types.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic.workspace = true
