[workspace]
resolver = "2"
members = ["bin/suix", "crates/grpc", "crates/rpc", "crates/vanity"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["longcipher"]
repository = "https://github.com/longcipher/suix"
readme = "README.md"
homepage = "https://github.com/longcipher/suix"
keywords = ["sui", "blockchain", "cli", "vanity-address", "grpc"]
categories = ["command-line-utilities", "cryptography"]

[workspace.dependencies]
anyhow = "1.0.104"
clap = "4.6.7"
color-eyre = "0.6.5"
eyre = "0.6.14"
grpc = { path = "crates/grpc" }
hex = "0.4.3"
rayon = "1.12.0"
regex = "1.13.1"
reqwest = "0.12"
rpc = { path = "crates/rpc" }
serde_json = "1.0.151"
sui-keys = { git = "https://github.com/MystenLabs/sui.git", rev = "be15a10386e78f5fa8d6be365a0fd228b22fa0c5" }
sui-rpc-api = { git = "https://github.com/MystenLabs/sui.git", rev = "be15a10386e78f5fa8d6be365a0fd228b22fa0c5" }
sui-types = { git = "https://github.com/MystenLabs/sui.git", rev = "be15a10386e78f5fa8d6be365a0fd228b22fa0c5" }
tokio = "1.52.1"
vanity = { path = "crates/vanity" }
