[package]
name = "keystore"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Local key management for suix: generate, import, export, list, sign, and multisig helpers."

[dependencies]
bcs.workspace = true
dirs.workspace = true
eyre.workspace = true
fastcrypto.workspace = true
hex.workspace = true
shared-crypto.workspace = true
sui-keys.workspace = true
sui-types.workspace = true
tokio = { workspace = true, features = ["full"] }
