[package]
name = "vanity"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Multi-threaded Sui vanity address generation with hexspeak, hex, and regex pattern matching."

[dependencies]
eyre = { workspace = true }
hex = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
sui-keys = { workspace = true }
sui-types = { workspace = true }
